// Generated by gencpp from file rr_plugin/AddGroup.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_ADDGROUP_H
#define RR_PLUGIN_MESSAGE_ADDGROUP_H

#include <ros/service_traits.h>


#include <rr_plugin/AddGroupRequest.h>
#include <rr_plugin/AddGroupResponse.h>


namespace rr_plugin
{

struct AddGroup
{

typedef AddGroupRequest Request;
typedef AddGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddGroup
} // namespace rr_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rr_plugin::AddGroup > {
  static const char* value()
  {
    return "2d1e218c6b1a35c7b53b671388d73073";
  }

  static const char* value(const ::rr_plugin::AddGroup&) { return value(); }
};

template<>
struct DataType< ::rr_plugin::AddGroup > {
  static const char* value()
  {
    return "rr_plugin/AddGroup";
  }

  static const char* value(const ::rr_plugin::AddGroup&) { return value(); }
};


// service_traits::MD5Sum< ::rr_plugin::AddGroupRequest> should match 
// service_traits::MD5Sum< ::rr_plugin::AddGroup > 
template<>
struct MD5Sum< ::rr_plugin::AddGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::AddGroup >::value();
  }
  static const char* value(const ::rr_plugin::AddGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::AddGroupRequest> should match 
// service_traits::DataType< ::rr_plugin::AddGroup > 
template<>
struct DataType< ::rr_plugin::AddGroupRequest>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::AddGroup >::value();
  }
  static const char* value(const ::rr_plugin::AddGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rr_plugin::AddGroupResponse> should match 
// service_traits::MD5Sum< ::rr_plugin::AddGroup > 
template<>
struct MD5Sum< ::rr_plugin::AddGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::AddGroup >::value();
  }
  static const char* value(const ::rr_plugin::AddGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::AddGroupResponse> should match 
// service_traits::DataType< ::rr_plugin::AddGroup > 
template<>
struct DataType< ::rr_plugin::AddGroupResponse>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::AddGroup >::value();
  }
  static const char* value(const ::rr_plugin::AddGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_ADDGROUP_H
