// Generated by gencpp from file rr_plugin/Contacts.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_CONTACTS_H
#define RR_PLUGIN_MESSAGE_CONTACTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rr_plugin/Contact.h>

namespace rr_plugin
{
template <class ContainerAllocator>
struct Contacts_
{
  typedef Contacts_<ContainerAllocator> Type;

  Contacts_()
    : Contacts()  {
    }
  Contacts_(const ContainerAllocator& _alloc)
    : Contacts(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rr_plugin::Contact_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rr_plugin::Contact_<ContainerAllocator> >::other >  _Contacts_type;
  _Contacts_type Contacts;




  typedef boost::shared_ptr< ::rr_plugin::Contacts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rr_plugin::Contacts_<ContainerAllocator> const> ConstPtr;

}; // struct Contacts_

typedef ::rr_plugin::Contacts_<std::allocator<void> > Contacts;

typedef boost::shared_ptr< ::rr_plugin::Contacts > ContactsPtr;
typedef boost::shared_ptr< ::rr_plugin::Contacts const> ContactsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rr_plugin::Contacts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rr_plugin::Contacts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rr_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rr_plugin': ['/home/turinglife/GPS_Project/RR_Robot/src/rr_plugin/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::Contacts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::Contacts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::Contacts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::Contacts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::Contacts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::Contacts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rr_plugin::Contacts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7aa4d50bde603c6f4ee8de785620b01";
  }

  static const char* value(const ::rr_plugin::Contacts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7aa4d50bde603c6ULL;
  static const uint64_t static_value2 = 0xf4ee8de785620b01ULL;
};

template<class ContainerAllocator>
struct DataType< ::rr_plugin::Contacts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_plugin/Contacts";
  }

  static const char* value(const ::rr_plugin::Contacts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rr_plugin::Contacts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_plugin/Contact[] Contacts\n\
\n\
================================================================================\n\
MSG: rr_plugin/Contact\n\
string collision1\n\
string collision2\n\
geometry_msgs/Vector3[] position\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::rr_plugin::Contacts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rr_plugin::Contacts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Contacts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Contacts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rr_plugin::Contacts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rr_plugin::Contacts_<ContainerAllocator>& v)
  {
    s << indent << "Contacts[]" << std::endl;
    for (size_t i = 0; i < v.Contacts.size(); ++i)
    {
      s << indent << "  Contacts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rr_plugin::Contact_<ContainerAllocator> >::stream(s, indent + "    ", v.Contacts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_CONTACTS_H
