// Generated by gencpp from file rr_plugin/DelGroup.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_DELGROUP_H
#define RR_PLUGIN_MESSAGE_DELGROUP_H

#include <ros/service_traits.h>


#include <rr_plugin/DelGroupRequest.h>
#include <rr_plugin/DelGroupResponse.h>


namespace rr_plugin
{

struct DelGroup
{

typedef DelGroupRequest Request;
typedef DelGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DelGroup
} // namespace rr_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rr_plugin::DelGroup > {
  static const char* value()
  {
    return "7d90912713b548daf0792e10bc03054b";
  }

  static const char* value(const ::rr_plugin::DelGroup&) { return value(); }
};

template<>
struct DataType< ::rr_plugin::DelGroup > {
  static const char* value()
  {
    return "rr_plugin/DelGroup";
  }

  static const char* value(const ::rr_plugin::DelGroup&) { return value(); }
};


// service_traits::MD5Sum< ::rr_plugin::DelGroupRequest> should match 
// service_traits::MD5Sum< ::rr_plugin::DelGroup > 
template<>
struct MD5Sum< ::rr_plugin::DelGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::DelGroup >::value();
  }
  static const char* value(const ::rr_plugin::DelGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::DelGroupRequest> should match 
// service_traits::DataType< ::rr_plugin::DelGroup > 
template<>
struct DataType< ::rr_plugin::DelGroupRequest>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::DelGroup >::value();
  }
  static const char* value(const ::rr_plugin::DelGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rr_plugin::DelGroupResponse> should match 
// service_traits::MD5Sum< ::rr_plugin::DelGroup > 
template<>
struct MD5Sum< ::rr_plugin::DelGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::DelGroup >::value();
  }
  static const char* value(const ::rr_plugin::DelGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::DelGroupResponse> should match 
// service_traits::DataType< ::rr_plugin::DelGroup > 
template<>
struct DataType< ::rr_plugin::DelGroupResponse>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::DelGroup >::value();
  }
  static const char* value(const ::rr_plugin::DelGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_DELGROUP_H
