// Generated by gencpp from file rr_plugin/GetGripperData.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_GETGRIPPERDATA_H
#define RR_PLUGIN_MESSAGE_GETGRIPPERDATA_H

#include <ros/service_traits.h>


#include <rr_plugin/GetGripperDataRequest.h>
#include <rr_plugin/GetGripperDataResponse.h>


namespace rr_plugin
{

struct GetGripperData
{

typedef GetGripperDataRequest Request;
typedef GetGripperDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGripperData
} // namespace rr_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rr_plugin::GetGripperData > {
  static const char* value()
  {
    return "41a15d5585d2a91cea5a35ba0f2c1927";
  }

  static const char* value(const ::rr_plugin::GetGripperData&) { return value(); }
};

template<>
struct DataType< ::rr_plugin::GetGripperData > {
  static const char* value()
  {
    return "rr_plugin/GetGripperData";
  }

  static const char* value(const ::rr_plugin::GetGripperData&) { return value(); }
};


// service_traits::MD5Sum< ::rr_plugin::GetGripperDataRequest> should match 
// service_traits::MD5Sum< ::rr_plugin::GetGripperData > 
template<>
struct MD5Sum< ::rr_plugin::GetGripperDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::GetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::GetGripperDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::GetGripperDataRequest> should match 
// service_traits::DataType< ::rr_plugin::GetGripperData > 
template<>
struct DataType< ::rr_plugin::GetGripperDataRequest>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::GetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::GetGripperDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rr_plugin::GetGripperDataResponse> should match 
// service_traits::MD5Sum< ::rr_plugin::GetGripperData > 
template<>
struct MD5Sum< ::rr_plugin::GetGripperDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::GetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::GetGripperDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::GetGripperDataResponse> should match 
// service_traits::DataType< ::rr_plugin::GetGripperData > 
template<>
struct DataType< ::rr_plugin::GetGripperDataResponse>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::GetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::GetGripperDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_GETGRIPPERDATA_H
