// Generated by gencpp from file rr_plugin/GetGripperDataRequest.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_GETGRIPPERDATAREQUEST_H
#define RR_PLUGIN_MESSAGE_GETGRIPPERDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rr_plugin
{
template <class ContainerAllocator>
struct GetGripperDataRequest_
{
  typedef GetGripperDataRequest_<ContainerAllocator> Type;

  GetGripperDataRequest_()
    : isDegree(false)  {
    }
  GetGripperDataRequest_(const ContainerAllocator& _alloc)
    : isDegree(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isDegree_type;
  _isDegree_type isDegree;




  typedef boost::shared_ptr< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGripperDataRequest_

typedef ::rr_plugin::GetGripperDataRequest_<std::allocator<void> > GetGripperDataRequest;

typedef boost::shared_ptr< ::rr_plugin::GetGripperDataRequest > GetGripperDataRequestPtr;
typedef boost::shared_ptr< ::rr_plugin::GetGripperDataRequest const> GetGripperDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rr_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rr_plugin': ['/home/turinglife/GPS_Project/RR_Robot/src/rr_plugin/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15892e785ecf795e381ae90bd587b371";
  }

  static const char* value(const ::rr_plugin::GetGripperDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15892e785ecf795eULL;
  static const uint64_t static_value2 = 0x381ae90bd587b371ULL;
};

template<class ContainerAllocator>
struct DataType< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_plugin/GetGripperDataRequest";
  }

  static const char* value(const ::rr_plugin::GetGripperDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isDegree\n\
";
  }

  static const char* value(const ::rr_plugin::GetGripperDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isDegree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGripperDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rr_plugin::GetGripperDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rr_plugin::GetGripperDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "isDegree: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isDegree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_GETGRIPPERDATAREQUEST_H
