// Generated by gencpp from file rr_plugin/SetFloat64MultiArrayRequest.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_SETFLOAT64MULTIARRAYREQUEST_H
#define RR_PLUGIN_MESSAGE_SETFLOAT64MULTIARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rr_plugin
{
template <class ContainerAllocator>
struct SetFloat64MultiArrayRequest_
{
  typedef SetFloat64MultiArrayRequest_<ContainerAllocator> Type;

  SetFloat64MultiArrayRequest_()
    : data()  {
    }
  SetFloat64MultiArrayRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloat64MultiArrayRequest_

typedef ::rr_plugin::SetFloat64MultiArrayRequest_<std::allocator<void> > SetFloat64MultiArrayRequest;

typedef boost::shared_ptr< ::rr_plugin::SetFloat64MultiArrayRequest > SetFloat64MultiArrayRequestPtr;
typedef boost::shared_ptr< ::rr_plugin::SetFloat64MultiArrayRequest const> SetFloat64MultiArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rr_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rr_plugin': ['/home/turinglife/GPS_Project/RR_Robot/src/rr_plugin/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_plugin/SetFloat64MultiArrayRequest";
  }

  static const char* value(const ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[]         data\n\
";
  }

  static const char* value(const ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloat64MultiArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rr_plugin::SetFloat64MultiArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_SETFLOAT64MULTIARRAYREQUEST_H
