// Generated by gencpp from file rr_plugin/SetFloat64MultiArray.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_SETFLOAT64MULTIARRAY_H
#define RR_PLUGIN_MESSAGE_SETFLOAT64MULTIARRAY_H

#include <ros/service_traits.h>


#include <rr_plugin/SetFloat64MultiArrayRequest.h>
#include <rr_plugin/SetFloat64MultiArrayResponse.h>


namespace rr_plugin
{

struct SetFloat64MultiArray
{

typedef SetFloat64MultiArrayRequest Request;
typedef SetFloat64MultiArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64MultiArray
} // namespace rr_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rr_plugin::SetFloat64MultiArray > {
  static const char* value()
  {
    return "c63bf8592d64621eba801bc64f49f640";
  }

  static const char* value(const ::rr_plugin::SetFloat64MultiArray&) { return value(); }
};

template<>
struct DataType< ::rr_plugin::SetFloat64MultiArray > {
  static const char* value()
  {
    return "rr_plugin/SetFloat64MultiArray";
  }

  static const char* value(const ::rr_plugin::SetFloat64MultiArray&) { return value(); }
};


// service_traits::MD5Sum< ::rr_plugin::SetFloat64MultiArrayRequest> should match 
// service_traits::MD5Sum< ::rr_plugin::SetFloat64MultiArray > 
template<>
struct MD5Sum< ::rr_plugin::SetFloat64MultiArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::SetFloat64MultiArray >::value();
  }
  static const char* value(const ::rr_plugin::SetFloat64MultiArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::SetFloat64MultiArrayRequest> should match 
// service_traits::DataType< ::rr_plugin::SetFloat64MultiArray > 
template<>
struct DataType< ::rr_plugin::SetFloat64MultiArrayRequest>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::SetFloat64MultiArray >::value();
  }
  static const char* value(const ::rr_plugin::SetFloat64MultiArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rr_plugin::SetFloat64MultiArrayResponse> should match 
// service_traits::MD5Sum< ::rr_plugin::SetFloat64MultiArray > 
template<>
struct MD5Sum< ::rr_plugin::SetFloat64MultiArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::SetFloat64MultiArray >::value();
  }
  static const char* value(const ::rr_plugin::SetFloat64MultiArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::SetFloat64MultiArrayResponse> should match 
// service_traits::DataType< ::rr_plugin::SetFloat64MultiArray > 
template<>
struct DataType< ::rr_plugin::SetFloat64MultiArrayResponse>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::SetFloat64MultiArray >::value();
  }
  static const char* value(const ::rr_plugin::SetFloat64MultiArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_SETFLOAT64MULTIARRAY_H
