// Generated by gencpp from file rr_plugin/SetGripperData.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_SETGRIPPERDATA_H
#define RR_PLUGIN_MESSAGE_SETGRIPPERDATA_H

#include <ros/service_traits.h>


#include <rr_plugin/SetGripperDataRequest.h>
#include <rr_plugin/SetGripperDataResponse.h>


namespace rr_plugin
{

struct SetGripperData
{

typedef SetGripperDataRequest Request;
typedef SetGripperDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGripperData
} // namespace rr_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rr_plugin::SetGripperData > {
  static const char* value()
  {
    return "ac17c576c6826b5f5e8daea06d6ed830";
  }

  static const char* value(const ::rr_plugin::SetGripperData&) { return value(); }
};

template<>
struct DataType< ::rr_plugin::SetGripperData > {
  static const char* value()
  {
    return "rr_plugin/SetGripperData";
  }

  static const char* value(const ::rr_plugin::SetGripperData&) { return value(); }
};


// service_traits::MD5Sum< ::rr_plugin::SetGripperDataRequest> should match 
// service_traits::MD5Sum< ::rr_plugin::SetGripperData > 
template<>
struct MD5Sum< ::rr_plugin::SetGripperDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::SetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::SetGripperDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::SetGripperDataRequest> should match 
// service_traits::DataType< ::rr_plugin::SetGripperData > 
template<>
struct DataType< ::rr_plugin::SetGripperDataRequest>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::SetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::SetGripperDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rr_plugin::SetGripperDataResponse> should match 
// service_traits::MD5Sum< ::rr_plugin::SetGripperData > 
template<>
struct MD5Sum< ::rr_plugin::SetGripperDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::SetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::SetGripperDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::SetGripperDataResponse> should match 
// service_traits::DataType< ::rr_plugin::SetGripperData > 
template<>
struct DataType< ::rr_plugin::SetGripperDataResponse>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::SetGripperData >::value();
  }
  static const char* value(const ::rr_plugin::SetGripperDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_SETGRIPPERDATA_H
