// Generated by gencpp from file rr_plugin/SetGripperDataRequest.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_SETGRIPPERDATAREQUEST_H
#define RR_PLUGIN_MESSAGE_SETGRIPPERDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rr_plugin
{
template <class ContainerAllocator>
struct SetGripperDataRequest_
{
  typedef SetGripperDataRequest_<ContainerAllocator> Type;

  SetGripperDataRequest_()
    : leftfingerpos(0.0)
    , rightfingerpos(0.0)  {
    }
  SetGripperDataRequest_(const ContainerAllocator& _alloc)
    : leftfingerpos(0.0)
    , rightfingerpos(0.0)  {
  (void)_alloc;
    }



   typedef double _leftfingerpos_type;
  _leftfingerpos_type leftfingerpos;

   typedef double _rightfingerpos_type;
  _rightfingerpos_type rightfingerpos;




  typedef boost::shared_ptr< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetGripperDataRequest_

typedef ::rr_plugin::SetGripperDataRequest_<std::allocator<void> > SetGripperDataRequest;

typedef boost::shared_ptr< ::rr_plugin::SetGripperDataRequest > SetGripperDataRequestPtr;
typedef boost::shared_ptr< ::rr_plugin::SetGripperDataRequest const> SetGripperDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rr_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rr_plugin': ['/home/turinglife/GPS_Project/RR_Robot/src/rr_plugin/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6b3a9f52fdc4cb419faefcd8977f359";
  }

  static const char* value(const ::rr_plugin::SetGripperDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6b3a9f52fdc4cb4ULL;
  static const uint64_t static_value2 = 0x19faefcd8977f359ULL;
};

template<class ContainerAllocator>
struct DataType< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_plugin/SetGripperDataRequest";
  }

  static const char* value(const ::rr_plugin::SetGripperDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 leftfingerpos\n\
float64 rightfingerpos\n\
";
  }

  static const char* value(const ::rr_plugin::SetGripperDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftfingerpos);
      stream.next(m.rightfingerpos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGripperDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rr_plugin::SetGripperDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rr_plugin::SetGripperDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "leftfingerpos: ";
    Printer<double>::stream(s, indent + "  ", v.leftfingerpos);
    s << indent << "rightfingerpos: ";
    Printer<double>::stream(s, indent + "  ", v.rightfingerpos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_SETGRIPPERDATAREQUEST_H
