// Generated by gencpp from file rr_plugin/SetPointRequest.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_SETPOINTREQUEST_H
#define RR_PLUGIN_MESSAGE_SETPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace rr_plugin
{
template <class ContainerAllocator>
struct SetPointRequest_
{
  typedef SetPointRequest_<ContainerAllocator> Type;

  SetPointRequest_()
    : type()
    , index(0)
    , point()  {
    }
  SetPointRequest_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , index(0)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef int8_t _index_type;
  _index_type index;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;




  typedef boost::shared_ptr< ::rr_plugin::SetPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rr_plugin::SetPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPointRequest_

typedef ::rr_plugin::SetPointRequest_<std::allocator<void> > SetPointRequest;

typedef boost::shared_ptr< ::rr_plugin::SetPointRequest > SetPointRequestPtr;
typedef boost::shared_ptr< ::rr_plugin::SetPointRequest const> SetPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rr_plugin::SetPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rr_plugin::SetPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rr_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rr_plugin': ['/home/turinglife/GPS_Project/RR_Robot/src/rr_plugin/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_plugin::SetPointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_plugin::SetPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_plugin::SetPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9578d3e8dc8c0fd774c80a138a1c988a";
  }

  static const char* value(const ::rr_plugin::SetPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9578d3e8dc8c0fd7ULL;
  static const uint64_t static_value2 = 0x74c80a138a1c988aULL;
};

template<class ContainerAllocator>
struct DataType< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_plugin/SetPointRequest";
  }

  static const char* value(const ::rr_plugin::SetPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n\
int8 index\n\
geometry_msgs/Point point\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::rr_plugin::SetPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.index);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rr_plugin::SetPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rr_plugin::SetPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.index);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_SETPOINTREQUEST_H
