// Generated by gencpp from file rr_plugin/SetPoint.msg
// DO NOT EDIT!


#ifndef RR_PLUGIN_MESSAGE_SETPOINT_H
#define RR_PLUGIN_MESSAGE_SETPOINT_H

#include <ros/service_traits.h>


#include <rr_plugin/SetPointRequest.h>
#include <rr_plugin/SetPointResponse.h>


namespace rr_plugin
{

struct SetPoint
{

typedef SetPointRequest Request;
typedef SetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPoint
} // namespace rr_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rr_plugin::SetPoint > {
  static const char* value()
  {
    return "8b2f9f6b13ea2dce923aca7be2a42f79";
  }

  static const char* value(const ::rr_plugin::SetPoint&) { return value(); }
};

template<>
struct DataType< ::rr_plugin::SetPoint > {
  static const char* value()
  {
    return "rr_plugin/SetPoint";
  }

  static const char* value(const ::rr_plugin::SetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::rr_plugin::SetPointRequest> should match 
// service_traits::MD5Sum< ::rr_plugin::SetPoint > 
template<>
struct MD5Sum< ::rr_plugin::SetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::SetPoint >::value();
  }
  static const char* value(const ::rr_plugin::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::SetPointRequest> should match 
// service_traits::DataType< ::rr_plugin::SetPoint > 
template<>
struct DataType< ::rr_plugin::SetPointRequest>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::SetPoint >::value();
  }
  static const char* value(const ::rr_plugin::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rr_plugin::SetPointResponse> should match 
// service_traits::MD5Sum< ::rr_plugin::SetPoint > 
template<>
struct MD5Sum< ::rr_plugin::SetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rr_plugin::SetPoint >::value();
  }
  static const char* value(const ::rr_plugin::SetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rr_plugin::SetPointResponse> should match 
// service_traits::DataType< ::rr_plugin::SetPoint > 
template<>
struct DataType< ::rr_plugin::SetPointResponse>
{
  static const char* value()
  {
    return DataType< ::rr_plugin::SetPoint >::value();
  }
  static const char* value(const ::rr_plugin::SetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RR_PLUGIN_MESSAGE_SETPOINT_H
